# Static Application Security Testing
name: "Bandit"

on:
    push:
        branches: [master]
        paths:
            - ".github/workflows/bandit.yml"
            - "**/*.py"
    pull_request:
        branches: [master]

permissions:
    contents: read

jobs:
    bandit:
        uses: Nicconike/Steam-Stats/.github/workflows/bandit.yml@master
