name: Scorecard Security

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

permissions:
    contents: read

jobs:
    scorecard:
        uses: Nicconike/Steam-Stats/.github/workflows/scorecard.yml@master
